### PR TITLE
Create Detox workflow for Github Actions

### PR DESCRIPTION
**Pull request by krnl-panic**
I've created this specific Detox E2E workflow that we'll be able to use to run our test suite at whatever interval is appropriate.

This workflow configures the environment in most of the same way as the fastlane build and deploy workflow.

### CODE REVIEW

**Comment by floridemai** [comment]
@mikeartfay The flow has changed and we have an age gate as the first screen. We can give it another go once this is fixed.

**Comment by krnl-panic** [comment]
@floridemai I've refactored the initial test to look at the age-check. This PR should be up to date with the main branch again.

**Comment by krnl-panic** [comment]
@floridemai Hi Paul! I've rebased this test workflow PR to resolve any conflicts with the main line branch. The checks have re-run as well. Assuming all is green, please let me know if we can merge this work. Thanks!

**Review by floridemai — APPROVED** [review]
@mikeartfay Feel free to merge when ready.

**Pull request closed without merging**
