### PR TITLE
Add NetInfo config with healthcheck URL

### PR DESCRIPTION
**Pull request by AlanSl**
Needs testing

### CODE REVIEW

**Review by floridemai — APPROVED** [review]
Good to go as long as long as `curl --location --head 'https://api.prd.ctprox.health.ny.gov/api/healthcheck' returns 204

**Comment by AlanSl** [comment]
@floridemai Looks like @colmharte wants to set up a new endpoint for this so let's see what happens there, I'll leave this in draft until that's resolved.

**Comment by AlanSl** [comment]
@floridemai The healthcheck URL returns 204 now so can you please re-do the tests we discussed

**Review by floridemai — APPROVED** [review]
Tested and all good. ✅

**Pull request merged**
