### PR TITLE
Failsafe for age gate screen

### PR DESCRIPTION
**Pull request by AlanSl**
For https://github.com/project-vagabond/covid-green-app/issues/512

I used the Android split screen feature to simulate small devices. Goals are:

 - In all reasonable, foreseeable scenarios (including a partially-sighted Russian non-English speaker using the smallest known device we support), show the full app logo, readable text, pressable button and DOH logo, as nicely spaced as possible 
 - In any possible unreasonable, unforeseeable scenarios (e.g. a fad for small square phones breaks out in October or there's some case we missed in testing), ensure that it degrades gracefully and the text and button are prioritised.

I've simulated that using the Android split screen feature. This is in Russian (longest text) at maximum enlarged font size in increasingly unreasonable scenarios:

 
This is it at normal font size:

### CODE REVIEW

**Comment by AlanSl** [comment]
It was a bit tight with both the maximum text size increase and the maximum Android "Screen Zoom" applied:



So I've lowered the maximum text size a bit further. It still comes out larger than a lot of the maximum-enlarged text in the app:

**Review by floridemai — APPROVED** [review]
I like the flexSpacer idea, I hate the whole approach we took for this screen. It won't pass a11y test if we were to be honest (on the very first screen... 😞 )

**Comment by AlanSl** [comment]
Latest commit centres things a little more nicely when everything isn't enlarged

**Comment by JohnAGill** [comment]
Tested on IOS 1st & 2nd gen SE, 8, 8 plus, 11, 11 pro max & XR

Tested initial install, restarting the app and deleting and reinstalling the app
Tested all of the above with largest text size for ios.
Only issue was on 1st gen SE with largest text size, but it's pretty minor

Screenshot 2020-09-23 at 16 18 04

**Comment by helloantoine** [comment]
Looks great. 
Also tested VoiceOver (iOS), Voice Access (Android) and TalkBack(Android). No problem. 


Great job!

**Pull request merged**
