### PR TITLE
proximity alert screen updates

### PR DESCRIPTION
**Pull request by floridemai**
Issue: https://github.com/project-vagabond/covid-green-app/issues/110

### CODE REVIEW

**Review by AlanSl — COMMENTED** [review]
We're missing the "get tested" section, is that intentional?

I think there was another issue for it

**Comment by AlanSl** [comment]
@floridemai  https://github.com/project-vagabond/covid-green-app/issues/111 includes new icon

**Review by AlanSl — APPROVED** [review]

**Comment by floridemai** [comment]
@AlanSl In order to avoid text duplicates I've split the top text and the list. Cause text  is not bold and has a title in the alert scren. Also addressed https://github.com/project-vagabond/covid-green-app/issues/97 - color is specific so i added it directly in the button 😬

**Comment by floridemai** [comment]
> We're missing the "get tested" section, is that intentional?
> 
> I think there was another issue for it



> @floridemai #111 includes new icon

I did that before in: https://github.com/project-vagabond/covid-green-app/pull/139. It's automatically picked  up.

**Pull request merged**
