### PR TITLE
Accurate bar charts, starting at 0, with trend line

### PR DESCRIPTION
**Pull request by AlanSl**
Several recent issues are closely related so I'll work on them together:

- [x] Switch charts to vertical bars https://github.com/project-vagabond/covid-green-app/issues/81
  - [x] Add 7-day rolling average line
  - [x] Add labelling to line (needs input on text)
- [x] Start the charts' Y-axis at 0 https://github.com/project-vagabond/covid-green-app/issues/80
- [x] Ensure the charts accurately represent the latest API data https://github.com/project-vagabond/covid-green-app/issues/79
- [x] No non-integers in y axis labels, and don't show very low numbers as spikes https://github.com/project-vagabond/covid-green-app/issues/94
- [x] Accomodate varied charting periods (change to 30 days as per  https://github.com/project-vagabond/covid-green-app/issues/78 needs to be done on the API side)

### CODE REVIEW

**Comment by AlanSl** [comment]
Not getting the 30-day data through the API yet, this is with fake data:

**Comment by AlanSl** [comment]
With latest commits fake data has been removed and it should be able to handle any amount of data, here is how it handles 7 days of data:

**Review by floridemai — APPROVED** [review]
LGTM

**Comment by mboskin** [comment]
Rated this as High because it contains multiple issues,

**Pull request merged**
