### PR TITLE
(WIP) Use react-native-accessible-selectable for checkboxes

### PR DESCRIPTION
**Pull request by AlanSl**
**This adds iOS native dependencies so:**

 - do cocoa pods install
 - check the iOS build still works as expected

For the issue described in this comment: https://github.com/project-vagabond/covid-green-app/issues/245#issuecomment-687514574

Without this, React state update re-render timings cause the old `accessibilityState` to be read before the new one on checking a checkbox: "Not chec... Checked" or "Chec... Not checked". 

This adds a dependency designed for exactly this problem that does some platform specific direct internal state updates to just say the new state.

### CODE REVIEW

**Comment by ShaunBaker** [comment]
@AlanSl Do we really need a dependency to manage this?

The issue comment linked is referring to TalkBack - which is Android and not iOS - but the dependency is for iOS from reading its README

**Comment by AlanSl** [comment]
I'm also having some issues with iOS builds.

So yeah maybe the better approach is to copy what it does on Android (which is all JS via UIManager etc and doesn't introduce any native deps) and revisit the iOS side only if it's flagged.

**Comment by floridemai** [comment]
@AlanSl @ShaunBaker Turns out that this is a "known" issue and if that library fixes it i'm ok with it. Unless @ShaunBaker you have ideas on how to do it better/quicker?

**Comment by AlanSl** [comment]
@floridemai Do you have the issue on iOS and if so does this fix it for you? I was having build problems on iOS.

My plan for this is to take the js they use for android, update it to typescript not flow and just use that (with credit). Less risky than using an old lib containing native deps and little activity for 2 years for the iOS side of the issue which hasn't been reported.

**Comment by floridemai** [comment]
> @floridemai Do you have the issue on iOS and if so does this fix it for you? I was having build problems on iOS.
> 
> My plan for this is to take the js they use for android, update it to typescript not flow and just use that (with credit). Less risky than using an old lib containing native deps and little activity for 2 years for the iOS side of the issue which hasn't been reported.

No, it's not working on iOS (unless i messed up something).
```
[!] use_native_modules! skipped the react-native dependency 'react-native-accessible-selectable'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

**Comment by AlanSl** [comment]
I'm closing this since it seems disproportionately problematic to the problem.

Some more testing suggests we can fix this more neatly if we can stop the async call to `app.setContext` from causing the accessible element to re-render. That's not easy, however.

**Pull request closed without merging**
